### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by Lurking9527** [cylonchau/firewalld-gateway#4]
大佬，你好，
我尝试使用您项目下的Dockerfile文件进行构建image，
结果提示失败：
docker build  -t firewalld-gateway:20230516 -f Dockerfile  . 
![image](https://github.com/cylonchau/firewalld-gateway/assets/46019214/0f2c5976-7a76-4013-bef9-cdbf38c3c090)

请问是什么原因没有成功生成二进制呢？

**Comment by cylonchau** [comment]
go 1.18 直接make build 可以生成 二进制文件，因为Dockerfile我这里还没有测试过，可能存在一点点问题，这一阵会提交上去。

**Comment by cylonchau** [comment]
Hi @Lurking9527 go1.18 直接make build 可以生成 二进制文件，docker部署的话，因为Dockerfile 我这里还没有测试过，可能存在一点点问题，这一阵会提交上去。

**Comment by Lurking9527** [comment]
感谢！我似乎发现了Dockerfile的问题,应该是路径写错了
![image](https://github.com/cylonchau/firewalld-gateway/assets/46019214/60c33438-6a47-4d04-8f5a-45f67f493df7)
但是我打包成功后docker run后，浏览器访问http://ip:2952,报错404
![image](https://github.com/cylonchau/firewalld-gateway/assets/46019214/84b5b8c8-b34e-4477-b633-6706248ab8e0)
是我的url不正确，或者是打的镜像有问题吗？

**Comment by cylonchau** [comment]
> 感谢！我似乎发现了Dockerfile的问题,应该是路径写错了 ![image](https://user-images.githubusercontent.com/46019214/238803281-60c33438-6a47-4d04-8f5a-45f67f493df7.png) 但是我打包成功后docker run后，浏览器访问[http://ip:2952,报错404](http://ip:2952,%E6%8A%A5%E9%94%99404) ![image](https://user-images.githubusercontent.com/46019214/238803435-84b5b8c8-b34e-4477-b633-6706248ab8e0.png) 是我的url不正确，或者是打的镜像有问题吗？

之前的dockerfile有问题，我上传了新的Dockerfile，之前的没有前端，而且如果可以使用，需要替换我编译好的firewalld来替换系统默认的firewalld，如果ubuntu/debian没有。则apt install就可以

**Comment by Lurking9527** [comment]
感谢大佬，
我使用您新的Dockerfile构建的image，docker run后，web似乎还是无法访问，可能还是有问题？
![image](https://github.com/cylonchau/firewalld-gateway/assets/46019214/ae3004b4-06f8-4eff-bc23-ea7425a5ad90)

![image](https://github.com/cylonchau/firewalld-gateway/assets/46019214/b3a38512-8e1a-4231-9607-87952c19e9ba)

**Comment by cylonchau** [comment]
@Lurking9527 对于firewalld部分，不需要重新打包，可以参考 [releases](https://github.com/cylonchau/firewalld/releases) 直接下载对应Linux发行版替换即可

例如 centos/redhat  rpm -e xxx --force  rpm -ivh xxxx

注意安装后需要配置的部分，配置dbus开启TCP，

关于DBus TCP 配置可以参考 http://darkdark.top/centos7-dbus-troubleshooting.html
关于DBUS ACL 策略方面可以参考 http://darkdark.top/dbus-security-policy.html
看你提到了你的操作系统是Centos7 下面是Centos7 的配置

修改 /etc/dbus-1/system.conf 如下

```xml

-->
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-Bus Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
<listen>tcp:host=10.0.0.3,bind=*,port=55556,family=ipv4</listen> 
<listen>unix:tmpdir=/tmp</listen>
  
<policy context="default">
    <allow user="root" />
    <allow own="com.github.cylonchau.Uranus" /> <!-- allow uranus resiger to dbus-daemon -->
    <!-- 这里是让 Uranus 可以通过注册到dbus上自己的名称，具体名称可以通过配置文件更改 -->
    <allow receive_sender="com.github.cylonchau.Uranus" receive_path="/org/fedoraproject/FirewallD1" />
</policy>

  <auth>ANONYMOUS</auth>
  <allow_anonymous/>
</busconfig>
```
更多的策略可以通过ACL与iptables进行限制。


已这些为基础，生成的主机均可被管理

**Comment by Lurking9527** [comment]
感谢！
![image](https://github.com/cylonchau/firewalld-gateway/assets/46019214/37052ebc-6c14-4620-8865-d1307ee97704)
您的rpm版本python-firewall-0.6.3-4.el7.noarch.rpm，似乎与我的客户端的版本并不能兼容,rpm -ivh时会有冲突。

**Comment by Lurking9527** [comment]
> 感谢！ ![image](https://user-images.githubusercontent.com/46019214/239422192-9e12c538-4a19-43af-a0dc-795294d9bc2d.png)
> 
> 您的rpm版本python-firewall-0.6.3-4.el7.noarch.rpm，似乎与我的客户端的版本并不能兼容,rpm -ivh时会有冲突。

rpm -e后，仍然需要安装firewalld rpm包，仍然会覆盖更新到firewalld-0.6.3-13.el7_9.noarch。

**Comment by cylonchau** [comment]
Firewalld包不用卸载，需要的直邮firewalld-python这个包，您只需要卸载或者覆盖这一个包就可以了

**Comment by Lurking9527** [comment]
好的，多谢，
但是我使用您的配置客户端：
![image](https://github.com/cylonchau/firewalld-gateway/assets/46019214/afda72a8-f8de-44e2-b899-b1ed6e725e02)
服务端报错：
![image](https://github.com/cylonchau/firewalld-gateway/assets/46019214/6696b8d0-168c-4e04-9a6c-9a8da1b79ad0)
为啥客户端55556端口似乎没有监听？

**Comment by cylonchau** [comment]
> 好的，多谢， 但是我使用您的配置客户端： ![image](https://user-images.githubusercontent.com/46019214/239472708-afda72a8-f8de-44e2-b899-b1ed6e725e02.png) 服务端报错： ![image](https://user-images.githubusercontent.com/46019214/239472895-6696b8d0-168c-4e04-9a6c-9a8da1b79ad0.png) 为啥客户端55556端口似乎没有监听？

监听是systemd做的，可以参考这篇文章修改systemd 配置文件 https://stackoverflow.com/questions/61327052/linux-dbus-remote-tcp-connection-with-systemd-fails
